// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUvTgNVh51c-rjZazCB6HAqgECVm4twO0',
    appId: '1:844611876388:web:1b5cb3c35362ed817f4ab1',
    messagingSenderId: '844611876388',
    projectId: 'gathering-525c5',
    authDomain: 'gathering-525c5.firebaseapp.com',
    storageBucket: 'gathering-525c5.firebasestorage.app',
    measurementId: 'G-KF8BYQRXK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB75s0uQdUza3VBhVfvrhFbuH2Qd7Zs0s0',
    appId: '1:844611876388:android:48b78e61599de31f7f4ab1',
    messagingSenderId: '844611876388',
    projectId: 'gathering-525c5',
    storageBucket: 'gathering-525c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_YoolJ1dkFgqTg5qiPxw9A5YhbWY-Y4',
    appId: '1:844611876388:ios:4cafc31811bf58b17f4ab1',
    messagingSenderId: '844611876388',
    projectId: 'gathering-525c5',
    storageBucket: 'gathering-525c5.firebasestorage.app',
    iosBundleId: 'com.example.gatheringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK_YoolJ1dkFgqTg5qiPxw9A5YhbWY-Y4',
    appId: '1:844611876388:ios:4cafc31811bf58b17f4ab1',
    messagingSenderId: '844611876388',
    projectId: 'gathering-525c5',
    storageBucket: 'gathering-525c5.firebasestorage.app',
    iosBundleId: 'com.example.gatheringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUvTgNVh51c-rjZazCB6HAqgECVm4twO0',
    appId: '1:844611876388:web:0cc63b2c8a5dbd407f4ab1',
    messagingSenderId: '844611876388',
    projectId: 'gathering-525c5',
    authDomain: 'gathering-525c5.firebaseapp.com',
    storageBucket: 'gathering-525c5.firebasestorage.app',
    measurementId: 'G-KNQNK97PCQ',
  );
}
